# Generated by Django 5.2.17 on 2026-09-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=120)),
                ('equipe', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dds', 'DDS'), ('ronda', 'Ronda'), ('vtr', 'VTR'), ('emergencia', 'Emergência'), ('avaliacao', 'Avaliação'), ('glp', 'Batedor de GLP'), ('fonte_radioativa', 'Fonte Radioativa'), ('inspecao_mensal', 'Inspeção Mensal'), ('trabalho_quente', 'Acompanhamento Trabalho a Quente'), ('treinamento', 'Treinamento'), ('caminhoes_combate', 'Caminhões de Combate')], max_length=30)),
                ('dados', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='registros.diario')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
