# Generated by Django 5.2.17 on 2026-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/'),
        ),
    ]
